### ISSUE TITLE
draggedListIndex null when moving item in top left

### ISSUE THREAD

**Issue by BenPoell** [jakebonk/FlutterBoardView#21]
Hi,

when moving an item from somewhere in the lists to the top left it occurs that the null-check of `draggedListIndex` fails.
![image](https://user-images.githubusercontent.com/24900930/151691615-9718ae32-b336-42e3-9dcd-8522bddf4e5f.png)

It seems that `.whenComplete((){` is somehow in the asyncronous call is called twice but I couldn't really dive deeper into the logic, maybe you have a clue.
![image](https://user-images.githubusercontent.com/24900930/151691637-ed6466c7-93c6-4a82-9b6f-4e4867d34a82.png)

Crash log:
```
I/flutter (13850): [2022-01-30 07:52:38.658171 | Catcher | INFO] ============================== CATCHER LOG ==============================
I/flutter (13850): [2022-01-30 07:52:38.658806 | Catcher | INFO] Crash occurred on 2022-01-30 07:52:38.657085
I/flutter (13850): [2022-01-30 07:52:38.659022 | Catcher | INFO]
I/flutter (13850): [2022-01-30 07:52:38.665425 | Catcher | INFO] ------- DEVICE INFO -------
I/flutter (13850): [2022-01-30 07:52:38.668144 | Catcher | INFO] id: RSR1.201013.001
I/flutter (13850): [2022-01-30 07:52:38.669514 | Catcher | INFO] androidId: a4eb8febffeede56
I/flutter (13850): [2022-01-30 07:52:38.671544 | Catcher | INFO] board: goldfish_x86
I/flutter (13850): [2022-01-30 07:52:38.673091 | Catcher | INFO] bootloader: unknown
I/flutter (13850): [2022-01-30 07:52:38.673414 | Catcher | INFO] brand: google
I/flutter (13850): [2022-01-30 07:52:38.673602 | Catcher | INFO] device: generic_x86_arm
I/flutter (13850): [2022-01-30 07:52:38.673771 | Catcher | INFO] display: sdk_gphone_x86_arm-userdebug 11 RSR1.201013.001 6903271 dev-keys
I/flutter (13850): [2022-01-30 07:52:38.674629 | Catcher | INFO] fingerprint: google/sdk_gphone_x86_arm/generic_x86_arm:11/RSR1.201013.001/6903271:userdebug/dev-keys
I/flutter (13850): [2022-01-30 07:52:38.675092 | Catcher | INFO] hardware: ranchu
I/flutter (13850): [2022-01-30 07:52:38.675526 | Catcher | INFO] host: abfarm-us-west1-c-0007
I/flutter (13850): [2022-01-30 07:52:38.675647 | Catcher | INFO] isPhysicalDevice: false
I/flutter (13850): [2022-01-30 07:52:38.675738 | Catcher | INFO] manufacturer: Google
I/flutter (13850): [2022-01-30 07:52:38.675944 | Catcher | INFO] model: sdk_gphone_x86_arm
I/flutter (13850): [2022-01-30 07:52:38.676414 | Catcher | INFO] product: sdk_gphone_x86_arm
I/flutter (13850): [2022-01-30 07:52:38.676522 | Catcher | INFO] tags: dev-keys
I/flutter (13850): [2022-01-30 07:52:38.676615 | Catcher | INFO] type: userdebug
I/flutter (13850): [2022-01-30 07:52:38.676703 | Catcher | INFO] versionBaseOs:
I/flutter (13850): [2022-01-30 07:52:38.676807 | Catcher | INFO] versionCodename: REL
I/flutter (13850): [2022-01-30 07:52:38.678090 | Catcher | INFO] versionIncremental: 6903271
I/flutter (13850): [2022-01-30 07:52:38.678334 | Catcher | INFO] versionPreviewSdk: 0
I/flutter (13850): [2022-01-30 07:52:38.678499 | Catcher | INFO] versionRelease: 11
I/flutter (13850): [2022-01-30 07:52:38.686513 | Catcher | INFO] versionSdk: 30
I/flutter (13850): [2022-01-30 07:52:38.686778 | Catcher | INFO] versionSecurityPatch: 2020-09-05
I/flutter (13850): [2022-01-30 07:52:38.686994 | Catcher | INFO]
I/flutter (13850): [2022-01-30 07:52:38.688534 | Catcher | INFO] ------- APP INFO -------
I/flutter (13850): [2022-01-30 07:52:38.689257 | Catcher | INFO] environment: debug
I/flutter (13850): [2022-01-30 07:52:38.689520 | Catcher | INFO] version: 0.9.1
I/flutter (13850): [2022-01-30 07:52:38.691351 | Catcher | INFO] appName: XXX
I/flutter (13850): [2022-01-30 07:52:38.691787 | Catcher | INFO] buildNumber: 202201291
I/flutter (13850): [2022-01-30 07:52:38.692339 | Catcher | INFO] packageName: XXX
I/flutter (13850): [2022-01-30 07:52:38.692592 | Catcher | INFO]
I/flutter (13850): [2022-01-30 07:52:38.692756 | Catcher | INFO] ---------- ERROR ----------
I/flutter (13850): [2022-01-30 07:52:38.692957 | Catcher | INFO] Null check operator used on a null value
I/flutter (13850): [2022-01-30 07:52:38.693181 | Catcher | INFO]
I/flutter (13850): [2022-01-30 07:52:38.693323 | Catcher | INFO] ------- STACK TRACE -------
I/flutter (13850): [2022-01-30 07:52:38.693588 | Catcher | INFO] #0      BoardViewState.build.<anonymous closure> package:boardview/boardview.dart:503
I/flutter (13850): [2022-01-30 07:52:38.694075 | Catcher | INFO] #1      _rootRun (dart:async/zone.dart:1420:47)
I/flutter (13850): [2022-01-30 07:52:38.694714 | Catcher | INFO] #2      _CustomZone.run (dart:async/zone.dart:1328:19)
I/flutter (13850): [2022-01-30 07:52:38.696102 | Catcher | INFO] #3      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:203:18)
I/flutter (13850): [2022-01-30 07:52:38.696368 | Catcher | INFO] #4      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:737:39)
I/flutter (13850): [2022-01-30 07:52:38.697425 | Catcher | INFO] #5      Future._propagateToListeners (dart:async/future_impl.dart:793:11)
I/flutter (13850): [2022-01-30 07:52:38.697798 | Catcher | INFO] #6      Future._completeWithValue (dart:async/future_impl.dart:602:5)
I/flutter (13850): [2022-01-30 07:52:38.698862 | Catcher | INFO] #7      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:264:13)
I/flutter (13850): [2022-01-30 07:52:38.700419 | Catcher | INFO] #8      ScrollController.animateTo (package:flutter/src/widgets/scroll_controller.dart)
package:flutter/…/widgets/scroll_controller.dart:1
I/flutter (13850): [2022-01-30 07:52:38.700765 | Catcher | INFO] <asynchronous suspension>
I/flutter (13850): [2022-01-30 07:52:38.701310 | Catcher | INFO]
I/flutter (13850): [2022-01-30 07:52:38.701552 | Catcher | INFO] ------- CUSTOM INFO -------
I/flutter (13850): [2022-01-30 07:52:38.701705 | Catcher | INFO] ======================================================================
```

**Comment by Vebion** [comment]
The same error occurs with any movement
